services:
  - type: web
    name: yolov8-object-detection-api
    env: docker
    plan: free
    region: ohio
    # Crucial: Tell Render the code is in the 'backend' folder
    rootDir: backend
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
    healthCheckPath: /health
